-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.institutions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  legal_name text NOT NULL,
  display_name text NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'suspended'::text, 'closed'::text])),
  t3_tenant_did text NOT NULL UNIQUE,
  settlement_profile_ref text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT institutions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.agent_authority_revocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  agent_did text NOT NULL,
  authority_ref text NOT NULL,
  reason text NOT NULL CHECK (reason = ANY (ARRAY['operator_revoked'::text, 'policy_replaced'::text, 'credential_compromised'::text, 'terminal3_revoked'::text])),
  revoked_by text NOT NULL,
  revoked_at timestamp with time zone NOT NULL DEFAULT now(),
  unrevoked_at timestamp with time zone,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_authority_revocations_pkey PRIMARY KEY (id),
  CONSTRAINT agent_authority_revocations_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.institutions(id)
);
CREATE TABLE public.completed_trades (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  trade_ref text NOT NULL UNIQUE,
  buy_institution_id uuid NOT NULL,
  sell_institution_id uuid NOT NULL,
  asset_code_ciphertext text NOT NULL CHECK (asset_code_ciphertext <> ''::text),
  quantity_ciphertext text NOT NULL CHECK (quantity_ciphertext <> ''::text),
  execution_price_ciphertext text NOT NULL CHECK (execution_price_ciphertext <> ''::text),
  settlement_status text NOT NULL CHECK (settlement_status = ANY (ARRAY['settled'::text, 'failed'::text, 'reversed'::text])),
  settled_at timestamp with time zone NOT NULL,
  t3_execution_ref text NOT NULL CHECK (t3_execution_ref <> ''::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  rail_id text,
  rail_trade_ref text,
  rail_state text CHECK (rail_state IS NULL OR (rail_state = ANY (ARRAY['settled'::text, 'failed'::text, 'reversed'::text]))),
  reconciled_at timestamp with time zone,
  negotiation_session_id uuid,
  CONSTRAINT completed_trades_pkey PRIMARY KEY (id),
  CONSTRAINT completed_trades_buy_institution_id_fkey FOREIGN KEY (buy_institution_id) REFERENCES public.institutions(id),
  CONSTRAINT completed_trades_sell_institution_id_fkey FOREIGN KEY (sell_institution_id) REFERENCES public.institutions(id),
  CONSTRAINT completed_trades_negotiation_session_id_fkey FOREIGN KEY (negotiation_session_id) REFERENCES public.negotiation_sessions(id)
);
CREATE TABLE public.audit_receipts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  completed_trade_id uuid NOT NULL,
  institution_id uuid NOT NULL,
  receipt_ciphertext text NOT NULL CHECK (receipt_ciphertext <> ''::text),
  receipt_hash text NOT NULL CHECK (receipt_hash <> ''::text),
  key_version text NOT NULL CHECK (key_version <> ''::text),
  t3_attestation_ref text NOT NULL CHECK (t3_attestation_ref <> ''::text),
  access_scope text NOT NULL CHECK (access_scope = ANY (ARRAY['buyer'::text, 'seller'::text, 'regulatory_export'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  opened_at timestamp with time zone,
  CONSTRAINT audit_receipts_pkey PRIMARY KEY (id),
  CONSTRAINT audit_receipts_completed_trade_id_fkey FOREIGN KEY (completed_trade_id) REFERENCES public.completed_trades(id),
  CONSTRAINT audit_receipts_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.institutions(id)
);
CREATE TABLE public.portfolios (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  asset_code text NOT NULL,
  balance numeric NOT NULL DEFAULT 0 CHECK (balance >= 0::numeric),
  locked numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT portfolios_pkey PRIMARY KEY (id),
  CONSTRAINT portfolios_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.institutions(id)
);
CREATE TABLE public.portfolio_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  asset_code text NOT NULL,
  delta numeric NOT NULL,
  balance_after numeric NOT NULL,
  change_type text NOT NULL CHECK (change_type = ANY (ARRAY['settlement_buy'::text, 'settlement_sell'::text, 'adjustment'::text, 'import'::text])),
  reference_type text,
  reference_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT portfolio_history_pkey PRIMARY KEY (id),
  CONSTRAINT portfolio_history_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.institutions(id)
);
CREATE TABLE public.api_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  label text NOT NULL CHECK (label <> ''::text AND char_length(label) <= 100),
  prefix text NOT NULL CHECK (prefix <> ''::text AND char_length(prefix) <= 16),
  scopes text NOT NULL DEFAULT 'agent:operate'::text CHECK (scopes <> ''::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  revoked_at timestamp with time zone,
  key_bcrypt text NOT NULL CHECK (key_bcrypt ~~ '$2%'::text),
  lookup_key text NOT NULL,
  CONSTRAINT api_keys_pkey PRIMARY KEY (id),
  CONSTRAINT api_keys_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.institutions(id)
);
CREATE TABLE public.agents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  agent_did text NOT NULL CHECK (agent_did <> ''::text),
  status text NOT NULL DEFAULT 'admitted'::text CHECK (status = ANY (ARRAY['admitted'::text, 'revoked'::text])),
  authority_ref text NOT NULL CHECK (authority_ref <> ''::text),
  label text CHECK (label IS NULL OR label <> ''::text AND char_length(label) <= 100),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  instrument_scope ARRAY,
  direction_scope ARRAY,
  max_notional numeric DEFAULT NULL::numeric,
  limit_reference text,
  policy_hash text,
  CONSTRAINT agents_pkey PRIMARY KEY (id),
  CONSTRAINT agents_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.institutions(id)
);
CREATE TABLE public.intent_locks (
  intent_handle text NOT NULL CHECK (intent_handle <> ''::text),
  institution_id uuid NOT NULL,
  asset_code text NOT NULL CHECK (asset_code <> ''::text),
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  correlation_ref text,
  agent_did text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT intent_locks_pkey PRIMARY KEY (intent_handle),
  CONSTRAINT intent_locks_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.institutions(id)
);
CREATE TABLE public.negotiation_mandates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  agent_id uuid NOT NULL,
  agent_did text NOT NULL CHECK (agent_did <> ''::text),
  asset_code text NOT NULL CHECK (asset_code <> ''::text),
  side text NOT NULL CHECK (side = ANY (ARRAY['buy'::text, 'sell'::text])),
  target_quantity numeric NOT NULL CHECK (target_quantity > 0::numeric),
  reference_price numeric NOT NULL CHECK (reference_price > 0::numeric),
  price_band_bps integer NOT NULL CHECK (price_band_bps >= 0 AND price_band_bps <= 100000),
  deadline timestamp with time zone NOT NULL,
  urgency text NOT NULL CHECK (urgency = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'critical'::text])),
  max_notional numeric NOT NULL CHECK (max_notional > 0::numeric),
  disclosable_claims ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  required_counterparty_claims jsonb NOT NULL DEFAULT '{}'::jsonb,
  counterparty_constraints jsonb NOT NULL DEFAULT '{}'::jsonb,
  operator_prompt text NOT NULL CHECK (operator_prompt <> ''::text),
  policy_hash text NOT NULL CHECK (policy_hash <> ''::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  objective text,
  execution_style text CHECK (execution_style IS NULL OR (execution_style = ANY (ARRAY['patient'::text, 'balanced'::text, 'aggressive'::text, 'relationship_first'::text, 'trust_first'::text]))),
  valuation_policy jsonb,
  concession_policy jsonb,
  disclosure_policy jsonb,
  approval_policy jsonb,
  counterparty_requirements jsonb,
  size_policy jsonb,
  time_window jsonb,
  operator_instructions text,
  minimum_quantity numeric,
  partial_execution_allowed boolean,
  derived_anchor_value numeric,
  derived_walkaway_min numeric,
  derived_walkaway_max numeric,
  derived_concession_budget_bps integer,
  derived_notional_ceiling numeric,
  decision_meta jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT negotiation_mandates_pkey PRIMARY KEY (id),
  CONSTRAINT negotiation_mandates_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.institutions(id),
  CONSTRAINT negotiation_mandates_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id)
);
CREATE TABLE public.negotiation_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_code text NOT NULL CHECK (asset_code <> ''::text),
  buy_institution_id uuid NOT NULL,
  sell_institution_id uuid NOT NULL,
  buy_agent_did text NOT NULL CHECK (buy_agent_did <> ''::text),
  sell_agent_did text NOT NULL CHECK (sell_agent_did <> ''::text),
  buy_mandate_id uuid NOT NULL,
  sell_mandate_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pairing'::text CHECK (status = ANY (ARRAY['pairing'::text, 'active'::text, 'awaiting_approval'::text, 'converged'::text, 'settling'::text, 'settled'::text, 'walked_away'::text, 'expired'::text])),
  current_turn text NOT NULL DEFAULT 'buy'::text CHECK (current_turn = ANY (ARRAY['buy'::text, 'sell'::text])),
  round_number integer NOT NULL DEFAULT 0 CHECK (round_number >= 0),
  max_rounds integer NOT NULL CHECK (max_rounds > 0),
  deadline timestamp with time zone NOT NULL,
  trade_ref text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  escalation_status text NOT NULL DEFAULT 'none'::text CHECK (escalation_status = ANY (ARRAY['none'::text, 'pending'::text, 'approved'::text, 'declined'::text])),
  escalation_initiated_round_id uuid,
  escalation_resolved_at timestamp with time zone,
  delegation_credentials jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT negotiation_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT negotiation_sessions_buy_institution_id_fkey FOREIGN KEY (buy_institution_id) REFERENCES public.institutions(id),
  CONSTRAINT negotiation_sessions_sell_institution_id_fkey FOREIGN KEY (sell_institution_id) REFERENCES public.institutions(id),
  CONSTRAINT negotiation_sessions_buy_mandate_id_fkey FOREIGN KEY (buy_mandate_id) REFERENCES public.negotiation_mandates(id),
  CONSTRAINT negotiation_sessions_sell_mandate_id_fkey FOREIGN KEY (sell_mandate_id) REFERENCES public.negotiation_mandates(id),
  CONSTRAINT negotiation_sessions_escalation_initiated_round_id_fkey FOREIGN KEY (escalation_initiated_round_id) REFERENCES public.negotiation_rounds(id)
);
CREATE TABLE public.negotiation_rounds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  round_number integer NOT NULL CHECK (round_number >= 0),
  actor_did text NOT NULL CHECK (actor_did <> ''::text),
  actor_side text NOT NULL CHECK (actor_side = ANY (ARRAY['buy'::text, 'sell'::text])),
  move_type text NOT NULL CHECK (move_type = ANY (ARRAY['propose'::text, 'counter'::text, 'reveal'::text, 'request_disclosure'::text, 'accept'::text, 'hold'::text, 'walkaway'::text])),
  proposal_ciphertext text,
  disclosed_claim_refs ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  opaque_signal text,
  reasoning text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  strategic_intent text,
  confidence numeric,
  escalation_requested boolean DEFAULT false,
  settlement_readiness text CHECK (settlement_readiness IS NULL OR (settlement_readiness = ANY (ARRAY['not_ready'::text, 'near'::text, 'ready'::text]))),
  CONSTRAINT negotiation_rounds_pkey PRIMARY KEY (id),
  CONSTRAINT negotiation_rounds_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.negotiation_sessions(id)
);
CREATE TABLE public.negotiation_disclosures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  from_did text NOT NULL CHECK (from_did <> ''::text),
  from_side text NOT NULL CHECK (from_side = ANY (ARRAY['buy'::text, 'sell'::text])),
  claim_type text NOT NULL CHECK (claim_type <> ''::text),
  claim_assertion_ciphertext text NOT NULL,
  verified boolean NOT NULL DEFAULT false,
  t3_attestation_ref text NOT NULL CHECK (t3_attestation_ref <> ''::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT negotiation_disclosures_pkey PRIMARY KEY (id),
  CONSTRAINT negotiation_disclosures_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.negotiation_sessions(id),
  CONSTRAINT negotiation_disclosures_claim_assertion_ciphertext_check CHECK (verified = false OR (verified = true AND claim_assertion_ciphertext <> ''::text))
);
CREATE TABLE public.published_contracts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tail text NOT NULL CHECK (tail <> ''::text),
  contract_version text NOT NULL CHECK (contract_version <> ''::text),
  network_env text NOT NULL CHECK (network_env = ANY (ARRAY['testnet'::text, 'production'::text])),
  tenant_did text NOT NULL CHECK (tenant_did <> ''::text),
  wasm_size integer NOT NULL CHECK (wasm_size > 0),
  handle text,
  published_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT published_contracts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tenant_identities (
  tenant_did text NOT NULL CHECK (tenant_did <> ''::text),
  signing_private_key text NOT NULL CHECK (signing_private_key ~ '^0x[0-9a-fA-F]{64}$'::text),
  signing_public_key text NOT NULL CHECK (signing_public_key ~ '^0x[0-9a-fA-F]{66}$'::text),
  signing_address text NOT NULL CHECK (signing_address ~ '^0x[0-9a-fA-F]{40}$'::text),
  issuer_did text NOT NULL CHECK (issuer_did ~~ 'did:ethr:0x%'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tenant_identities_pkey PRIMARY KEY (tenant_did)
);